-- Analytics D1 schema
--
-- anonymous_installations: mỗi installation một dòng
--   installation_hash TEXT       PK, SHA-256 của UUID localStorage
--   origin            TEXT       ustudy.hakhoi.io.vn | ustudy.unopia.io.vn
--   first_seen_day    TEXT       ngày đầu hoạt động, YYYY-MM-DD
--   last_seen_day     TEXT       ngày hoạt động gần nhất, YYYY-MM-DD
--   app_version       TEXT       phiên bản app gần nhất
--   client_kind       TEXT       hiện tại là 'web'
--   deleted_day       TEXT NULL  ngày user xóa ID thống kê; NULL = đang hoạt động
--
-- installation_activity_days: một dòng cho mỗi installation mỗi ngày hoạt động
--   installation_hash TEXT       FK -> anonymous_installations.installation_hash
--   active_day        TEXT       ngày hoạt động, YYYY-MM-DD
--   PRIMARY KEY (installation_hash, active_day)
--
-- Ghi chú:
--   - Hai bảng liên kết bằng installation_hash.
--   - Hash vẫn là ID giả danh; tránh SELECT hash ra kết quả nếu không cần.
--   - Mỗi snapshot chứa dữ liệu của một domain; local query chạy riêng từng snapshot.

